// Generated by CoffeeScript 1.10.0

/*
http://hitokoto.cn/
简单来说，一言（ヒトコト）指的是就是一句话，可以是动漫中的台词，可以是小说中的语句，也可以是网络上的各种小段子。
或是感动，或是开心，又或是单纯的回忆，来到这里，留下你所喜欢的那一句句话，与大家分享，这就是一言存在的目的。
 */

var request = require('request');

(function() {
  module.exports = function(content, send, robot, message) {
    if (!content.match(/^hitokoto/)) {
      return;
    }

    var url = 'http://api.hitokoto.cn/'
    if (content.match(/^hitokoto\s*help\s*/)) {
      
      fs.readFile('/Users/ShinCurry/Downloads/0067sJVNgw1f8rymvwm7pj308c08cmxi.jpg', 'utf8', function(err, data) {
        if (err) {
          send(err)
        }
        send(data)
      });
      //send('hitokoto anime/comic/game/novel');
      return;
    } else if (content.match(/^hitokoto\s*anime\s*$/)) {
      url += '?c=a';
    } else if (content.match(/^hitokoto\s*comic\s*$/)) {
      url += '?c=b';
    } else if (content.match(/^hitokoto\s*game\s*$/)) {
      url += '?c=c';
    } else if (content.match(/^hitokoto\s*novel\s*$/)) {
      url += '?c=d';
    } else if (content.match(/^hitokoto\s*other\s*$/)) {
      var i = int(Math.random()*10)
      var p = ['e', 'f', 'g']
      url += '?c='+p[i];
    }

    request(url, function (error, response, body) {
        if (!error && response.statusCode == 200) {
          var data = JSON.parse(body);
          send('「' + data.hitokoto + '」 ---- ' + data.from);
        } else {
          send('请求 Hitokoto 失败了 _(:зゝ∠)_');
        }
    });
  };

}).call(this);
